name = "SciMLDocs"
uuid = "9802be14-e95c-4933-b545-e41021dbf0cf"
authors = ["SciML"]
version = "1.1.0"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
