name = "SciMLDocs"
uuid = "9802be14-e95c-4933-b545-e41021dbf0cf"
authors = ["SciML"]
version = "1.7.0"

[deps]

[compat]
julia = "1.10"

[extras]
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ExplicitImports", "Test"]
